[project]
name = "Examples"
author = "Susa Milan Mihaly"
exec_entry = "main.gh"

[clibs]
clibs = [
  { name = "core", path = "clibs/core.so", flags = [
    "",
  ] },
  { name = "GC", path = "clibs/libgc.so", flags = [
  ] },
]

